# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bins',
            fields=[
                ('bin_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('access_key', models.CharField(max_length=10)),
                ('land_mark', models.CharField(max_length=20)),
            ],
        ),
    ]
