# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bins',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bins',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
