# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartbin', '0002_auto_20171130_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='bin_info',
            fields=[
                ('bin_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('access_key', models.CharField(max_length=10)),
                ('land_mark', models.CharField(max_length=20)),
                ('current_level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='fill_level_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('bin_level', models.FloatField()),
                ('bin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartbin.bin_info')),
            ],
        ),
        migrations.DeleteModel(
            name='bins',
        ),
    ]
