# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbin', '0003_auto_20171202_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill_level_stats',
            name='id',
        ),
        migrations.AlterField(
            model_name='bin_info',
            name='current_level',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fill_level_stats',
            name='bin_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
